#!/bin/bash
# Cloudflare Pages Deployment - "summary to team"
# Step-by-step guide

echo "🚀 Cloudflare Pages Deployment Checklist"
echo "==========================================="
echo ""

# Step 1
echo "✅ STEP 1: Push code to GitHub"
echo "   Commands:"
echo "   $ git init"
echo "   $ git add ."
echo "   $ git commit -m 'Deploy to Cloudflare Pages'"
echo "   $ git branch -M main"
echo "   $ git remote add origin <your-github-repo-url>"
echo "   $ git push -u origin main"
echo ""

# Step 2
echo "✅ STEP 2: Connect Cloudflare Account"
echo "   1. Go to https://dash.cloudflare.com"
echo "   2. Pages → Create a project"
echo "   3. Connect Git → Select GitHub"
echo "   4. Authorize and select 'STTfinalsammary' repo"
echo ""

# Step 3
echo "✅ STEP 3: Build Configuration"
echo "   1. Select 'main' branch"
echo "   2. Build settings:"
echo "      - Framework: None (Static site)"
echo "      - Build command: (leave empty)"
echo "      - Build output directory: web/"
echo "   3. Save and deploy"
echo ""

# Step 4
echo "✅ STEP 4: Set Environment Variables"
echo "   1. In Cloudflare Pages → Settings → Environment variables"
echo "   2. Add variable:"
echo "      Name: BACKEND_URL"
echo "      Value: https://your-backend-server.com (or ngrok URL)"
echo "   3. Save"
echo ""

# Step 5
echo "✅ STEP 5: Backend Setup (Choose ONE)"
echo ""
echo "   Option A: Use ngrok (Temporary)"
echo "   ---------------------------------"
echo "   1. $ pip install pyngrok"
echo "   2. $ python run.py web  (run your current server)"
echo "   3. In another terminal:"
echo "        $ ngrok http 8000"
echo "   4. Copy the URL and set as BACKEND_URL in CF"
echo ""
echo "   Option B: Deploy to Render (Permanent)"
echo "   ---------------------------------"
echo "   1. Create render.yaml:"
echo "      services:"
echo "        - type: web"
echo "          name: stt-backend"
echo "          env: python"
echo "          startCommand: python run.py web"
echo "          envVars:"
echo "            - key: PORT"
echo "              value: '8000'"
echo "   2. Push to GitHub"
echo "   3. Go to render.com"
echo "   4. New → Web Service → Connect GitHub"
echo "   5. Deploy and get URL"
echo "   6. Set BACKEND_URL in Cloudflare Pages"
echo ""
echo "   Option C: Deploy to fly.io"
echo "   ---------------------------------"
echo "   1. $ npm install -g flyctl"
echo "   2. $ flyctl launch  (follow prompts)"
echo "   3. $ flyctl deploy"
echo "   4. Get URL and set as BACKEND_URL"
echo ""

# Step 6
echo "✅ STEP 6: Test Deployment"
echo "   1. Visit: https://summary-to-team.pages.dev"
echo "   2. Upload an audio file"
echo "   3. Check browser console (F12) for errors"
echo "   4. Monitor backend logs"
echo ""

echo "✅ FINAL CHECKLIST"
echo "  ✓ Code pushed to GitHub"
echo "  ✓ Cloudflare Pages connected"
echo "  ✓ Build settings configured"
echo "  ✓ BACKEND_URL environment variable set"
echo "  ✓ Backend server running (ngrok/Render/fly.io)"
echo "  ✓ Frontend loads at https://summary-to-team.pages.dev"
echo "  ✓ API calls reach backend server"
echo ""
echo "🎉 Done! Your app is live on Cloudflare!"
